// front-end/src/pages/dashboard/components/avatar/Avatar.tsx
import React, { useState } from 'react';

import './Avatar.scss';

export const Avatar = ({ logout, src }: { logout: () => void; src: string }) => {
  const [isOpenMenu, setOpenMenu] = useState(false);

  const closeMenu = () => setOpenMenu(false);
  const openMenu = () => setOpenMenu(true);

  return (
    <div onClick={() => openMenu()} className="avatar">
      {src && <img src={src} alt="Avatar of user" />}

      {isOpenMenu && (
        <div onMouseLeave={() => closeMenu()} className="avatar__menu">
          <ul>
            <li>
              <a href="/products-creator">Creator of product</a>
            </li>

            <li onClick={logout}>Log out</li>
          </ul>
        </div>
      )}
    </div>
  );
};

export default Avatar;

// front-end/angular/src/app/domain/dashboard/components/avatar/avatar.component.ts
import { Component, input, output, signal } from '@angular/core';
import { Role } from '@core/models';

@Component({
  selector: 'app-avatar',
  imports: [],
  templateUrl: './avatar.component.html',
  styleUrl: './avatar.component.scss',
  standalone: true,
})
export class AvatarComponent {
  public readonly role = input<Role>('STANDARD');
  public readonly src = input<string>('');

  public readonly logout = output<void>();

  protected readonly isOpenMenu = signal<boolean>(false);

  protected closeMenu(): void {
    this.isOpenMenu.set(false);
  }

  protected openMenu(): void {
    this.isOpenMenu.set(true);
  }
}

<div (click)="openMenu()" class="avatar">
  @if (src(); as src) {
    <img [src]="src" alt="AvatarComponent of user" />
  }

  @if (isOpenMenu()) {
    <div (mouseleave)="closeMenu()" class="avatar__menu">
      <ul>
        @if (role() === 'ADMIN') {
          <li>
            <a href="/products-creator">Creator of product</a>
          </li>
        }

        <li (click)="logout.emit()">Log out</li>
      </ul>
    </div>
  }
</div>
