// front-end/angular/src/app/domain/dashboard/components/rates/rates.component.ts
import { Component, input, output, signal } from '@angular/core';

@Component({
  selector: 'app-rates',
  imports: [],
  templateUrl: './rates.component.html',
  styleUrl: './rates.component.scss',
  standalone: true,
})
export class RatesComponent {
  public readonly confirmedRating = input<number>(0);

  public readonly selectRates = output<number>();

  protected readonly rating = signal<number>(0);

  protected handleMouseEnter(hoveredRating: number): void {
    this.rating.set(hoveredRating);
    console.log(hoveredRating);
  }

  protected handleMouseLeave(): void {
    this.rating.set(0);
  }

  protected handleClick(clickedRating: number): void {
    this.rating.set(clickedRating);
    this.selectRates.emit(clickedRating);
  }
}

<div class="rates">
  @for (value of [1, 2, 3, 4, 5]; track value) {
    <button
      (click)="handleClick(value)"
      (mouseenter)="handleMouseEnter(value)"
      (mouseleave)="handleMouseLeave()"
    >
      <img
        class="rates__item"
        [class.rates__item--filled]="value <= (rating() || confirmedRating() || 0)"
        [src]="
          '/icons/' +
          (value <= (rating() || confirmedRating() || 0) ? 'star-filled' : 'star') +
          '.svg'
        "
        alt=""
      />
    </button>
  }
</div>

// front-end/src/pages/dashboard/components/rates/Rates.tsx
import React, { useState } from 'react';
import classNames from 'classnames';

import './Rates.scss';

export const Rates = ({
  confirmedRating,
  selectRates
}: {
  confirmedRating: number;
  selectRates: (rating: number) => void;
}) => {
  const [rating, setRating] = useState(0);

  const handleMouseEnter = (hoveredRating: number) => setRating(hoveredRating);

  const handleMouseLeave = () => setRating(0);

  const handleClick = (clickedRating: number) => {
    setRating(clickedRating);
    selectRates(clickedRating);
  };

  return (
    <div className="rates">
      {Array.from(Array(5).keys()).map((value: number) => (
        <img
          onClick={() => handleClick(value + 1)}
          onMouseEnter={() => handleMouseEnter(value + 1)}
          onMouseLeave={handleMouseLeave}
          className={classNames({
            rates__item: true,
            'rates__item--filled': value + 1 <= (rating || confirmedRating)
          })}
          key={value}
          role="button"
          src={`/icons/${value + 1 <= (rating || confirmedRating) ? 'star-filled' : 'star'}.svg`}
        />
      ))}
    </div>
  );
};

export default Rates;
