// front-end/src/pages/dashboard/components/product/Product.tsx
import React, { useState } from 'react';

import { Product as ProductModel } from '../../../../models';
import { Rates } from '../rates';

import './Product.scss';

export const Product = ({
  product: { description, productsImages, isPromo, name, rate },
  index
}: {
  product: ProductModel;
  index: number;
}) => {
  const [imageIndex, setImageIndex] = useState(0);
  const [confirmedRating, setConfirmedRating] = useState(rate || 0);

  const selectRates = (rating: number) => {
    setConfirmedRating(rating);
    console.log(rating);
  };

  const showDetails = () => {
    return;
  };

  return (
    <div className="product">
      <div className="product__image">
        {isPromo && <div className="product__promo">Promo</div>}

        <img
          alt=""
          className="w-100"
          src={`http://localhost:5000${productsImages[imageIndex].path}`}
        />
      </div>

      <div className="product__content">
        <h4>{name}</h4>
        <p>{description.length > 100 ? description.slice(0, 150) + '...' : description}</p>

        <Rates confirmedRating={confirmedRating} selectRates={selectRates} />

        <button onClick={() => showDetails()} type="button">
          Show details
        </button>
      </div>
    </div>
  );
};

export default Product;

// front-end/angular/src/app/domain/dashboard/components/product/product.component.ts
import { Component, input, output, signal } from '@angular/core';
import { ButtonComponent } from '@shared/components';
import { RatesComponent } from '../rates/rates.component';
import { ProductImage } from '@core/models';
import { SafeHtmlPipe } from '@shared/pipes';

@Component({
  selector: 'app-product',
  imports: [ButtonComponent, RatesComponent, SafeHtmlPipe],
  templateUrl: './product.component.html',
  styleUrl: './product.component.scss',
  standalone: true,
})
export class ProductComponent {
  public readonly confirmedRating = input<number>(0);
  public readonly description = input<string>('');
  public readonly images = input<ProductImage[]>([]);
  public readonly isPromo = input<boolean>();
  public readonly name = input<string>();

  public readonly selectRates = output<number>();
  public readonly showDetails = output<void>();

  protected readonly imageIndex = signal<number>(0);
}

<div class="product">
  <div class="product__image">
    @if (isPromo()) {
      <div class="product__promo">Promo</div>
    }

    @if (images()[imageIndex()]?.path; as path) {
      <img alt="" class="w-100" [src]="path" />
    }
  </div>

  <div class="product__content">
    <h4>{{ name() }}</h4>

    <div [innerHTML]="description() | safeHtml"></div>

    <app-rates [confirmedRating]="confirmedRating()" (selectRates)="selectRates.emit($event)" />

    <app-button (callback)="showDetails.emit()" type="button"> Show details </app-button>
  </div>
</div>
