// front-end/src/components/files-uploader/FilesUploader.tsx
import React, { ChangeEvent, useState } from 'react';

import { Button } from '../button/Button';

import './FilesUploader.scss';

export const FilesUploader = ({
  accept,
  change,
  chooseImageMessage = 'Choose image for avatar to upload (PNG, JPG)',
  emptyMessage = 'No file currently selected for upload',
  multiple = false,
  name,
  placeholder = 'Select file'
}: {
  accept: string;
  change: (event: ChangeEvent<HTMLInputElement>) => void;
  chooseImageMessage?: string;
  emptyMessage?: string;
  multiple?: boolean;
  name: string;
  placeholder?: string;
}) => {
  const [files, setFiles] = useState<FileList | null>(null);
  const inputRef = React.createRef<HTMLInputElement>();

  return (
    <div className="files-uploader">
      <label className="files-uploader__choose-image-message" htmlFor="image">
        {chooseImageMessage}
      </label>

      <Button click={() => inputRef.current?.click()} theme="secondary">
        {placeholder}
      </Button>

      <input
        ref={inputRef}
        onChange={(event: ChangeEvent<HTMLInputElement>) => {
          change(event);
          setFiles(event.target.files);
        }}
        accept={accept}
        className="d-none"
        multiple={multiple}
        name={name}
        type="file"
      />

      {files?.length ? (
        <div className="files-uploader__files">
          {Array.from(files).map((file: File) => (
            <img className="w-100" key={file.name} src={URL.createObjectURL(file)} />
          ))}
        </div>
      ) : (
        <div className="files-uploader__preview">
          <p>{emptyMessage}</p>
        </div>
      )}
    </div>
  );
};

// front-end/angular/src/app/shared/components/files-uploader/files-uploader.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  input,
  output,
  viewChild,
} from '@angular/core';

@Component({
  selector: 'app-files-uploader',
  standalone: true,
  templateUrl: './files-uploader.component.html',
  styleUrl: './files-uploader.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FilesUploaderComponent {
  public readonly accept = input<string>('');
  public readonly chooseImageMessage = input<string>(
    'Choose image for avatar to upload (PNG, JPG)',
  );
  public readonly emptyMessage = input<string>('No file currently selected for upload');
  public readonly multiple = input<boolean>(false);
  public readonly name = input.required<string>();
  public readonly placeholder = input<string>('Select file');

  public readonly change = output<Event>();

  private readonly fileInput = viewChild<ElementRef<HTMLInputElement>>('fileInput');

  files: File[] = [];

  protected getPreviewUrl(file: File): string {
    return URL.createObjectURL(file);
  }

  protected openFileDialog(): void {
    this.fileInput()?.nativeElement.click();
  }

  protected onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;

    this.files = input.files ? Array.from(input.files) : [];

    this.change.emit(event);
  }
}

<div class="files-uploader">
  <p>
    {{ chooseImageMessage() }}
  </p>

  <button type="button" class="btn btn-secondary" (click)="openFileDialog()">
    {{ placeholder() }}
  </button>

  <input
    #fileInput
    class="d-none"
    type="file"
    [accept]="accept()"
    [multiple]="multiple()"
    [name]="name()"
    (change)="onFileChange($event)"
  />

  @if (files.length) {
    <div class="files-uploader__files">
      @for (file of files; track file.name) {
        <img class="w-100" [src]="getPreviewUrl(file)" [alt]="file.name" />
      }
    </div>
  } @else {
    <div class="files-uploader__preview">
      <p>{{ emptyMessage() }}</p>
    </div>
  }
</div>
